url:
baseurl: 
# Site settings
title: Test - Contact Form
email: sidimar@gmail.com
description: "Contact form provided for a test."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 9c4f33
  secondary: 9c4f33


# Postal address (add as many lines as necessary)
address:
  - line: 21 The Hops - James's Walk Street,
  - line: Dublin 8, Ireland

# Build settings
markdown: kramdown
